modLoader="javafml"
loaderVersion="[47,)"
license="Academic Free License v3.0"

[[mods]]
modId="cac"
version="1.4.0"
displayName="CaC"
displayURL="https://github.com/IIOwOII"
credits="Created using mod maker MCreator and Me..."
authors="OwO"
description="Chasing and Chased!"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.cac]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.cac]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration